// ==UserScript==
// @name         Khuddam Email Scraper - Loader
// @namespace    http://tampermonkey.net/
// @version      2.4
// @description  Loads main script from GitHub with notifications (scheduled & recurring)
// @match        https://software.khuddam.de/tajneed/index/
// @match        https://software.khuddam.de/maal/list_budget_overview/
// @grant        GM_xmlhttpRequest
// @connect      api.github.com
// @connect      raw.githubusercontent.com
// ==/UserScript==

(function() {
    'use strict';

    // ============================================
    // 🔧 USER CONFIGURATION - EDIT THIS SECTION
    // ============================================
    const USER_CONFIG = {
        // Personal Information
        DESIGNATION: "Qaid Majlis",
        SIGNATURE_NAME: "Qaid Name Here",
        TELEPHONE: "+49 123 456789",

        // UI Settings
        BUTTON_TEXT: "Send_Email",
        BUTTON_BG: "#fbbd00"
    };

    // GitHub File Settings
    const FILENAME = "chanda-emailer-main.js";         // Main script filename
    const NOTIFICATION_FILE = "notifications.json";     // Notifications filename

    // ============================================
    // 🔐 DEVELOPER SECTION - OBFUSCATED CREDENTIALS
    // ============================================

    // Paste the array generated by the Developer Tool here:
    const _0x = ['c','2','N','y','c','H','R','z','Z','z','I','=','Y','W','1','p','a','G','1','h','Z', '2', 'l', '0', 'a', 'H', 'V', 'i', 'X', '3', 'B', 'h', 'd', 'F', '8', 'x', 'M', 'U', 'J', 'Q', 'U', 'V', 'J', 'Q', 'Q', '1', 'k', 'w', 'e', 'X', 'Q', '0', 'b', '0', 'd', 'W', 'U', '0', 'F', 'V', 'a', 'H', 'c', '0', 'X', '0', 'F', 'j', 'R', 'G', 'l', 'q', 'U', 'G', '8', '2', 'V', 'W', 'x', 'q', 'd', '1', 'J', 'D', 'd', 'G', 'J', 'L', 'e', 'E', 'Q', '4', 'b', 'l', 'Q', 'x', 'c', 'F', 'p', 'N', 'Z', 'D', 'B', 'O', 'T', 'k', 'd', 'm', 'Q', '0', 'N', 'P', 'Q', 'n', 'B', 'G', 'U', 'F', 'l', 'R', 'S', 'G', 's', '0', 'M', 'j', 'Z', 'E', 'S', 'U', 'd', 'X', 'S', '1', 'F', 'T', 'e', 'n', 'p', 'I', 'Z', 'k', '0', 'z']

    // Boundary values (update these based on Developer Tool output)
    const _b1 = 12;   // End of repo (REPLACE WITH YOUR VALUE)
    const _b2 = 20;   // End of username (REPLACE WITH YOUR VALUE)

    // ============================================
    // 🔓 CREDENTIAL RECONSTRUCTION
    // ============================================
    function _decode() {
        let u = '', r = '', p = '';

        for (let i = 0; i < _0x.length; i++) {
            if (i < _b1) {
                r += _0x[i];
            } else if (i >= _b1 && i < _b2) {
                u += _0x[i];
            } else {
                p += _0x[i];
            }
        }

        return {
            username: atob(u),
            repo: atob(r),
            pat: atob(p)
        };
    }

    // ============================================
    // 🔤 UTF-8 BASE64 DECODER
    // ============================================
    function base64DecodeUnicode(base64Str) {
        base64Str = base64Str.replace(/\n/g, '');
        const binaryString = atob(base64Str);
        const bytes = new Uint8Array(binaryString.length);
        for (let i = 0; i < binaryString.length; i++) {
            bytes[i] = binaryString.charCodeAt(i);
        }
        return new TextDecoder('utf-8').decode(bytes);
    }

    // ============================================
    // 🔗 BUILD GITHUB API URL
    // ============================================
    function buildGitHubAPIURL(creds, filename) {
        return `https://api.github.com/repos/${creds.username}/${creds.repo}/contents/${filename}`;
    }

    // ============================================
    // 📅 DATE HELPER FUNCTIONS
    // ============================================
    function parseDate(dateStr) {
        if (!dateStr) return null;
        return new Date(dateStr);
    }

    function getCalendarDate(date) {
        return date.toISOString().split('T')[0]; // Returns YYYY-MM-DD
    }

    function getCalendarWeek(date) {
        const year = date.getFullYear();
        const firstDay = new Date(year, 0, 1);
        const days = Math.floor((date - firstDay) / (24 * 60 * 60 * 1000));
        return `${year}-W${Math.ceil((days + firstDay.getDay() + 1) / 7)}`;
    }

    function getCalendarMonth(date) {
        return date.toISOString().substring(0, 7); // Returns YYYY-MM
    }

    function shouldShowAgain(lastSeenTimestamp, frequency) {
        if (!lastSeenTimestamp || !frequency) return true;

        const now = new Date();
        const lastSeen = new Date(lastSeenTimestamp);

        // Parse frequency (e.g., "6h", "1d", "1w", "1m")
        const value = parseFloat(frequency);
        const unit = frequency.replace(/[0-9.]/g, '');

        switch(unit) {
            case 'h': { // Hours - exact time
                const hoursPassed = (now - lastSeen) / (1000 * 60 * 60);
                return hoursPassed >= value;
            }
            case 'd': { // Days - calendar date
                return getCalendarDate(now) !== getCalendarDate(lastSeen);
            }

            case 'w':{ // Weeks - calendar week
                return getCalendarWeek(now) !== getCalendarWeek(lastSeen);
            }

            case 'm': {  // Months - calendar month
                return getCalendarMonth(now) !== getCalendarMonth(lastSeen);
            }
            default:
                return true;
        }
    }

    // ============================================
    // 🔔 NOTIFICATION SYSTEM
    // ============================================
    function loadNotifications() {
        const creds = _decode();
        const apiURL = buildGitHubAPIURL(creds, NOTIFICATION_FILE);

        GM_xmlhttpRequest({
            method: "GET",
            url: apiURL,
            headers: {
                "Authorization": "Bearer " + creds.pat,
                "Accept": "application/vnd.github.v3+json",
                "User-Agent": "Tampermonkey-Script"
            },
            onload: function(response) {
                if (response.status === 200) {
                    try {
                        const data = JSON.parse(response.responseText);
                        const notificationData = JSON.parse(base64DecodeUnicode(data.content));

                        processNotification(notificationData);
                    } catch (error) {
                        console.warn('⚠️ Notification parsing failed:', error);
                    }
                } else {
                    console.log('ℹ️ No notifications file found (this is optional)');
                }
            },
            onerror: function() {
                console.log('ℹ️ Could not load notifications (optional feature)');
            }
        });
    }

    function processNotification(notification) {
        const { id, message, type, startDate, expires, frequency } = notification;
        const now = new Date();

        // Check start date
        if (startDate) {
            const start = parseDate(startDate);
            if (now < start) {
                console.log('ℹ️ Notification not started yet:', id);
                return;
            }
        }

        // Check expiry date
        if (expires) {
            const expiryDate = parseDate(expires);
            if (now > expiryDate) {
                console.log('ℹ️ Notification expired:', id);
                return;
            }
        }

        // Check if should show (based on frequency)
        const storageKey = `khuddam_notification_${id}`;
        const stored = localStorage.getItem(storageKey);

        if (stored) {
            const data = JSON.parse(stored);

            if (!frequency) {
                // One-time notification - already seen
                console.log('ℹ️ One-time notification already seen:', id);
                return;
            }

            if (!shouldShowAgain(data.lastSeen, frequency)) {
                console.log('ℹ️ Frequency not met yet:', id);
                return;
            }
        }

        // Show notification
        showNotification(message, type || 'info', () => {
            // Save timestamp when closed
            localStorage.setItem(storageKey, JSON.stringify({
                lastSeen: new Date().toISOString(),
                count: stored ? JSON.parse(stored).count + 1 : 1
            }));
        });
    }

    function showNotification(message, type = 'info', onClose) {
        const colors = {
            success: '#4CAF50',
            warning: '#ff9800',
            error: '#f44336',
            info: '#2196F3'
        };

        const icons = {
            success: '✓',
            warning: '⚠️',
            error: '✕',
            info: 'ℹ️'
        };

        const notification = document.createElement('div');
        notification.innerHTML = `
            <div style="display: flex; align-items: flex-start; gap: 10px;">
                <span style="font-size: 18px; flex-shrink: 0;">${icons[type]}</span>
                <div style="flex: 1;">${message}</div>
                <button class="close-btn" style="
                    background: transparent;
                    border: none;
                    color: white;
                    font-size: 20px;
                    cursor: pointer;
                    padding: 0;
                    margin: 0;
                    line-height: 1;
                    flex-shrink: 0;
                    width: 20px;
                    height: 20px;
                    display: flex;
                    align-items: center;
                    justify-content: center;
                    opacity: 0.8;
                    transition: opacity 0.2s;
                ">✕</button>
            </div>
        `;

        notification.style.cssText = `
            position: fixed;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            padding: 20px 25px;
            background: ${colors[type]};
            color: white;
            border-radius: 8px;
            box-shadow: 0 8px 24px rgba(0,0,0,0.4);
            z-index: 999999;
            font-family: Arial, sans-serif;
            font-size: 14px;
            max-width: 500px;
            min-width: 300px;
            line-height: 1.6;
            animation: fadeIn 0.3s ease-out;
        `;

        // Add animation
        const style = document.createElement('style');
        style.textContent = `
            @keyframes fadeIn {
                from {
                    opacity: 0;
                    transform: translate(-50%, -50%) scale(0.9);
                }
                to {
                    opacity: 1;
                    transform: translate(-50%, -50%) scale(1);
                }
            }
            .close-btn:hover {
                opacity: 1 !important;
                transform: scale(1.1);
            }
        `;
        document.head.appendChild(style);

        // Close button handler
        const closeBtn = notification.querySelector('.close-btn');
        closeBtn.onclick = function() {
            notification.style.transition = 'opacity 0.3s, transform 0.3s';
            notification.style.opacity = '0';
            notification.style.transform = 'translate(-50%, -50%) scale(0.9)';
            setTimeout(() => {
                notification.remove();
                if (onClose) onClose();
            }, 300);
        };

        // Style links in message
        notification.querySelectorAll('a').forEach(link => {
            link.style.color = '#fff';
            link.style.textDecoration = 'underline';
            link.style.fontWeight = 'bold';
        });

        document.body.appendChild(notification);
    }

    // ============================================
    // 📥 FETCH AND EXECUTE MAIN SCRIPT
    // ============================================
    function loadMainScript() {
        const creds = _decode();
        const apiURL = buildGitHubAPIURL(creds, FILENAME);

        console.log('🔄 Loading script from GitHub API...');
        console.log('📍 Repository:', `${creds.username}/${creds.repo}`);
        console.log('📄 File:', FILENAME);

        GM_xmlhttpRequest({
            method: "GET",
            url: apiURL,
            headers: {
                "Authorization": "Bearer " + creds.pat,
                "Accept": "application/vnd.github.v3+json",
                "User-Agent": "Tampermonkey-Script"
            },
            onload: function(response) {
                if (response.status === 200) {
                    try {
                        const data = JSON.parse(response.responseText);

                        if (!data.content) {
                            throw new Error('No content found in response');
                        }

                        const scriptContent = base64DecodeUnicode(data.content);

                        const configInjection = `
                            const INJECTED_CONFIG = ${JSON.stringify(USER_CONFIG)};
                        `;

                        const fullScript = configInjection + "\n\n" + scriptContent;
                        eval(fullScript);

                        console.log('✅ Khuddam Scraper loaded successfully!');
                        console.log('📊 Script size:', scriptContent.length, 'bytes');
                        console.log('✓ UTF-8 characters preserved (═══ and ───)');

                    } catch (error) {
                        console.error('❌ Error processing script:', error);
                        showError('Script processing failed: ' + error.message);
                    }
                } else if (response.status === 404) {
                    console.error('❌ File not found (404)');
                    console.error('📍 URL:', apiURL);
                    showError('File not found! Check:<br>• Filename: ' + FILENAME + '<br>• Repository access<br>• File exists in main branch');
                } else if (response.status === 401 || response.status === 403) {
                    console.error('❌ Authentication failed:', response.status);
                    showError('Authentication failed!<br>• Check your PAT token<br>• Ensure PAT has "repo" permission<br>• Token might be expired');
                } else {
                    console.error('❌ Unexpected status:', response.status);
                    console.error('📄 Response:', response.responseText);
                    showError(`Unexpected error (Status: ${response.status})`);
                }
            },
            onerror: function(error) {
                console.error('❌ Network error:', error);
                console.error('📍 URL:', apiURL);
                showError('Network error. Check your internet connection.');
            }
        });
    }

    // ============================================
    // 🚨 ERROR NOTIFICATION
    // ============================================
    function showError(message) {
        const notification = document.createElement('div');
        notification.innerHTML = `
            <strong>⚠️ Loader Error</strong><br>
            ${message}
        `;
        notification.style.cssText = `
            position: fixed;
            top: 20px;
            right: 20px;
            padding: 15px 20px;
            background: #f44336;
            color: white;
            border-radius: 5px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.3);
            z-index: 999999;
            font-family: Arial, sans-serif;
            font-size: 13px;
            max-width: 350px;
            line-height: 1.6;
        `;
        document.body.appendChild(notification);

        setTimeout(() => {
            notification.style.transition = 'opacity 0.5s';
            notification.style.opacity = '0';
            setTimeout(() => notification.remove(), 500);
        }, 10000);
    }

    // ============================================
    // 🚀 INITIALIZE
    // ============================================
    function init() {
        // Load notifications first
        loadNotifications();

        // Then load main script
        loadMainScript();
    }

    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', init);
    } else {
        init();
    }

})();
